# Generated by Django 5.1.4 on 2025-02-13 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=5000)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=155)),
                ("description", models.CharField(max_length=5000)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "priority",
                    models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], max_length=12),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[("BUG", "Bug"), ("IMPROVEMENT", "Improvement"), ("TASK", "Task")], max_length=12
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=[("TODO", "To-do"), ("WIP", "WIP"), ("DONE", "Done")], max_length=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=155)),
                ("description", models.CharField(max_length=5000)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BACKEND", "Back-end"),
                            ("FRONTEND", "Front-end"),
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
