# Generated by Django 5.1.4 on 2025-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_contributor_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type_development",
            field=models.CharField(
                choices=[("BACK-END", "BACK-END"), ("FRONT-END", "FRONT-END"), ("IOS", "IOS"), ("ANDROID", "ANDROID")],
                max_length=12,
            ),
        ),
    ]
