# Generated by Django 5.1.4 on 2025-01-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_issue_author_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="author_user_id",
            new_name="author",
        ),
    ]
