# Generated by Django 5.1.4 on 2025-01-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_author_user_id_issue_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(blank=True, related_name="contributed_projects", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="contributors_set", to="api.project"
            ),
        ),
    ]
