# Generated by Django 5.1.4 on 2025-01-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_project_contributors_alter_contributor_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="contributors",
        ),
    ]
