# Generated by Django 5.1.4 on 2025-01-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_project_contributors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
