# Generated by Django 5.1.4 on 2025-01-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_created_at_comment_created_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="description",
        ),
    ]
