# Generated by Django 5.1.4 on 2025-01-27 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_rename_text_comment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
