# Generated by Django 5.1.4 on 2025-02-02 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_project_created_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("project", "user")},
        ),
    ]
