# Generated by Django 5.1.4 on 2025-02-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="username",
        ),
    ]
